<?php

use Flavorly\LaravelHelpers\Helpers\AsciiTransliteration\AsciiTransliteration;

it('transliterates strings correctly', function ($input, $expected) {
    expect((new AsciiTransliteration())->transliterate($input))->toBe($expected);
})->with([
    ['', ''],
    ["\x00\x01\t\n\x1f ~\x7f", "\x00\x01\t\n\x1f ~\x7f"],
    ['sample', 'sample'],
    ['René François Lacôte', 'Rene Francois Lacote'],
    ['Blöße', 'Blosse'],
    ['Trần Hưng Đạo', 'Tran Hung Dao'],
    ['Nærøy', 'Naeroy'],
    ['Φειδιππίδης', 'Feidippidis'],
    ['Δημήτρης Φωτόπουλος', 'Dimitris Fotopoylos'],
    ['Борис Николаевич Ельцин', "Boris Nikolaevich El'tsin"],
    ['Володимир Горбулін', 'Volodimir Gorbulin'],
    ['Търговище', "T'rgovishche"],
    ['深圳', 'ShenZhen'],
    ['深水埗', 'ShenShuiBu'],
    ['화성시', 'HwaSeongSi'],
    ['華城市', 'HuaChengShi'],
    ['さいたま', 'saitama'],
    ['埼玉県', 'QiYuXian'],
    ['ደብረ ዘይት', 'debre zeyt'],
    ['ደቀምሓረ', "dek'emhare"],
    ['دمنهور', 'dmnhwr'],
    ['Աբովյան', 'Abovyan'],
    ['სამტრედია', "samt'redia"],
    ['אברהם הלוי פרנקל', "'vrhm hlvy frnkl"],
    ['⠠⠎⠁⠽⠀⠭⠀⠁⠛', '+say x ag'],
    ['ময়মনসিংহ', 'mymnsimh'],
    ['ထန်တလန်', 'thntln'],
    ['પોરબંદર', 'porbmdr'],
    ['महासमुंद', 'mhasmumd'],
    ['ಬೆಂಗಳೂರು', 'bemgluru'],
    ['សៀមរាប', 'siemrab'],
    ['ສະຫວັນນະເຂດ', 'sahvannaekhd'],
    ['കളമശ്ശേരി', 'klmsseri'],
    ['ଗଜପତି', 'gjpti'],
    ['ਜਲੰਧਰ', 'jlmdhr'],
    ['රත්නපුර', 'rtnpur'],
    ['கன்னியாகுமரி', 'knniyakumri'],
    ['శ్రీకాకుళం', 'srikakulm'],
    ['สงขลา', 'sngkhla'],
    ['👑 🌴', ':crown: :palm_tree:'],
    ['☆ ♯ ♰ ⚄ ⛌', '* # + 5 X'],
    ['№ ℳ ⅋ ⅍', 'No M & A/S'],
    ['トヨタ', 'toyota'],
    ['ߞߐߣߊߞߙߌ߫', 'konakri'],
    ['𐬰𐬀𐬭𐬀𐬚𐬎𐬱𐬙𐬭𐬀', 'zarathushtra'],
    ['ⵜⵉⴼⵉⵏⴰⵖ', 'tifinagh'],
    ['𐍅𐌿𐌻𐍆𐌹𐌻𐌰', 'wulfila'],
    ['ދިވެހި', 'dhivehi'],
    ['ᨅᨔ ᨕᨘᨁᨗ', 'bs ugi'],
    ['ϯⲙⲓⲛϩⲱⲣ', 'timinhor'],
    ['𐐜 𐐢𐐮𐐻𐑊 𐐝𐐻𐐪𐑉', 'Dh Litl Star'],
    ['ꁌꐭꑤ', 'pujjytxiep'],
    ['ⰳⰾⰰⰳⱁⰾⰹⱌⰰ', 'glagolica'],
    ['ᏎᏉᏯ', 'SeQuoYa'],
    ['ㄓㄨㄤ ㄅㄥ ㄒㄧㄠ', 'zhuang beng xiao'],
    ['ꚩꚫꛑꚩꚳ ꚳ꛰ꛀꚧꚩꛂ', "ipareim m'shuoiya"],
    ['ᓀᐦᐃᔭᐍᐏᐣ', 'nehiyawewin'],
    ['ᠤᠯᠠᠭᠠᠨᠴᠠᠪ', 'ulaganqab'],
    ['𐑨𐑯𐑛𐑮𐑩𐑒𐑤𐑰𐑟 𐑯 𐑞 𐑤𐑲𐑩𐑯', "andr'kliiz n dh lai'n"],
]);
